Routines = new Mongo.Collection('routines');
ArmExercises = new Mongo.Collection('armExercises');
ChestExercises = new Mongo.Collection('chestExercises');
LegExercises = new Mongo.Collection('legExercises');
CoreExercises = new Mongo.Collection('coreExercises');
RunningCardio = new Mongo.Collection('running');
EllipticalWorkout = new Mongo.Collection('ellipticalWorkout');
StairMasterWorkout = new Mongo.Collection('stairMasterWorkout');
CyclingCardio = new Mongo.Collection('cyclingCardio');
SwimmingWorkout = new Mongo.Collection('swimmingWorkout');
WalkingCardio = new Mongo.Collection('walkingCardio');
Stretch = new Mongo.Collection('stretch');
YogaFlex = new Mongo.Collection('yogaFlex');
PilatesFlex = new Mongo.Collection('pilatesFlex');
Exercises = new Mongo.Collection('exercises');
// Profiles = new Meteor.Collection('profiles');

Intermediate = new Mongo.Collection('intermediate');
Completed = new Mongo.Collection('completed'); //This will be for completed exercises